### ISSUE TITLE
V2 is on the way

### ISSUE THREAD

**Issue by sarink** [sarink/react-file-drop#23]
Hey guys, I am working on a v2 of this library which will fix all issues, and work with the latest React. Please stay tuned the next couple of weeks!
Until then, happy to accept PRs that would contain a temporary fix for any problems (maybe through a flag or some option, as to not break backwards compatibility)
Thanks!

**Comment by nbcnc** [comment]
@sarink, it's great to hear you're working on V2.  I really like your file-drop component.  It's been great to use in my project.   Thank you!! 

If I can make one suggestion --

In the current version of `react-file-drop`, the `onDrop` callback is triggering twice for me.  After doing some debugging, I realized that your `onDrop` prop is receiving **two** events for every drop -- 1) a Native onDrop Event and 2) a Proxy Event from React (I'm using V15.6.1).  

So whenever I drop a file into the drop area, two events were firing, causing my upload script to the fire twice, too.

```
<FileDrop frame={document}
      onDrop={this.onFileDrop}
      onFrameDragEnter={this.onDragEnter}
      onFrameDragLeave={this.onDragLeave}
      targetAlwaysVisible={true}/>
```

For my purposes, I fixed this by testing whether the `event` passed by `onDrop` also contains a `nativeEvent` object.  If `event.nativeEvent` does not return `undefined` then I know it's React's Proxy Event (which is sufficient for the onDrop event) and I can ignore the superfluous Native DOM onDrop Event and prevent the double-firing.

```
  onFileDrop = (files, event) => {

    // Disables Native Event -- relying on Proxy Event -- prevents double firing
    if (!event.nativeEvent) {
      return;
    }

    _.forEach(files, file => {
      this.data.set(file.name, file);
    });

    this.onUpload();

}
```

This fix was easy, but I'm not sure if there's a way your V2 component can be aware that, under some circumstances, both Native Events and Proxy Events could be triggered with each onDrop event and then somehow filter out one or the other so that they both don't fire at once in your code.

Thanks,
marc

**Comment by likerRr** [comment]
@sarink hi! How the progress goes?

**Comment by sarink** [comment]
Real life has gotten in the way, unfortunately. But this is still very high on my to-do list, and it's coming soon, I promise!

**Comment by sarink** [comment]
@likerRr This has been released!
@nbcnc can you explain what causes this and attempt to reproduce it in v2?
Thanks!
